"""empty message

Revision ID: 2a627b5960c1
Revises: None
Create Date: 2014-04-04 19:01:14.652634

"""

# revision identifiers, used by Alembic.
revision = '2a627b5960c1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('slide')
    op.drop_table('subject')
    op.drop_table('concept')
    op.drop_table('topic')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'role')
    op.drop_column('user', 'lastseen')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastseen', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('role', sa.SMALLINT(), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(length=80), nullable=True))
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(length=80), nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=80), nullable=True))
    op.add_column('user', sa.Column('surname', sa.VARCHAR(length=110), nullable=True))
    op.create_table('topic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic_name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('topic_des', sa.TEXT(), nullable=True),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], [u'subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('concept_name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('concept_des', sa.TEXT(), nullable=True),
    sa.Column('topic_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], [u'topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject_name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('subject_des', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slide',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slide_name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('slide_text', sa.TEXT(), nullable=True),
    sa.Column('concept_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], [u'concept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('list')
    ### end Alembic commands ###
